apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-mirror-v2
spec:
  destination:
    name: reviews
  precedence: 5
  mirror:
    name: details
    labels:
      version: v1