---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-products-api
spec:
  destination:
    name: productpage
  match:
    source:
      labels:
        istio: ingress
    request:
      headers:
        uri:
          prefix: /api/v1/products
  precedence: 3
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-productpage-logout
spec:
  destination:
    name: productpage
  match:
    source:
      labels:
        istio: ingress
    request:
      headers:
        uri:
          exact: /logout
  precedence: 3
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-productpage-login
spec:
  destination:
    name: productpage
  match:
    source:
      labels:
        istio: ingress
    request:
      headers:
        uri:
          exact: /login
  precedence: 3
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ingress-productpage-landing
spec:
  destination:
    name: productpage
  match:
    source:
      labels:
        istio: ingress
    request:
      headers:
        uri:
          exact: /productpage
  precedence: 3
  route:
  - labels:
      version: v1

