---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: productpage-deny-all
spec:
  destination:
    name: productpage
  match:
    source:
      labels:
        istio: ingress
  precedence: 1
  route:
  - weight: 100
  httpFault:
    abort:
      percent: 100
      httpStatus: 403